Lightweight storefront: Fetch pages for WP sites
woocommerce/woocommerce-ios pull request #11453
Opened 2023-12-14 08:36 UTC by itsmeichigo

Closes: #11451 

## Description

This PR updates the Networking and Yosemite layers to support fetching pages for WP sites. This will come in handy for preview WP themes.

Changes:
- Networking: Added a new model `WordPressPage`, new mapper `WordPressPageListMapper` and updated `WordPressSiteRemote` with a new endpoint for loading pages given a site URL.
- Yosemite: Updated the `WordPressSiteStore` and action to support the new endpoint.

## Testing instructions

The new endpoint hasn't been integrated yet, just CI passing should be sufficient.

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-12-15 06:41 UTC, hafizrahman requested changes
Sorry for not mentioning this earlier: An extra thing that was discovered was that for Attar theme, it has a https://attardemo.wordpress.com/ address.

These are non-atomic sites, so we need to use the WordPress.com public API endpoint instead:

`https://public-api.wordpress.com/rest/v1.1/sites/attardemo.wordpress.com/posts/?type=page&pretty=true`

ref: 

p1701445367276559-slack-C03L1NF1EA3

2023-12-15 10:06 UTC, itsmeichigo commented
@hafizrahman I clarified with the team in that thread and we decided not to handle the wpcom endpoint. For the Attar theme, we'll just hide the page switcher. Please the a look at this PR when you get a chance.

2023-12-17 09:44 UTC, hafizrahman approved these changes

2023-12-17 09:51 UTC, hafizrahman commented
This looks good. I'm merging it right away so I can work on the page selector/bottom sheet loading during the weekend.

2023-12-17 10:39 UTC, merged