[Woo POS] M2: Payment success UI update
woocommerce/woocommerce-ios pull request #13528
Opened 2024-08-07 12:00 UTC by staskus

Closes: #13344

## Description

Making payment success UI update. Leaving animation of the success icon out of scope.

## Solution

1. Added `wooCommerceEmerald` palette so it could be accessed the same way as `wooCommercePurple`
2. Updated success view spacing, and style
3. Replaced success image with SF symbol
4. Passed `Order` to `PointOfSaleCardPresentPaymentSuccessMessageViewModel` to show the order total. Made it testable by injecting currency formatter
5. Updated new order button layout
6. Added animations to transition from payment processing to success state

## Steps to reproduce

## Testing information

## Screenshots

https://github.com/user-attachments/assets/8019c4e6-3ee4-46ee-b6ba-ed734e2cc369

---
- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] This PR includes refactoring; smoke testing of the entire section is needed.

2024-08-07 12:00 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: View files have been modified,...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-08 05:01 UTC, iamgabrielma approved these changes
Works great! Just left a couple of questions, feel free to address anything in this PR, or in a different one if needed.

:shipit:

2024-08-08 05:01 UTC, iamgabrielma commented on WooFoundation/WooFoundation/Colors/UIColor+SemanticColors.swift
> +    class func wooCommerceEmerald(_ shade: ColorStudioShade) -> UIColor {
💯

2024-08-08 05:01 UTC, iamgabrielma commented on WooCommerce/WooCommerceTests/POS/ViewModels/PointOfSaleCardPresentPaymentSuccessMessageViewModelTests.swift
> +    func testMessage_order_has_total_and_currency() {
Nit:

```suggestion
    func test_message_order_has_total_and_currency() {
```

2024-08-08 05:01 UTC, iamgabrielma commented on WooCommerce/WooCommerceTests/POS/ViewModels/PointOfSaleCardPresentPaymentSuccessMessageViewModelTests.swift
> +    func testMessage_no_order() {
Nit: 

```suggestion
    func test_message_no_order() {
```

2024-08-08 05:01 UTC, iamgabrielma commented on WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleCardPresentPaymentInLineMessage.swift
> +import struct Yosemite.Order
Not specifically for this PR, but something I think we need to tackle before gets bigger: The usage of `Yosemite.Order` here is something that came up on [a different PR](https://github.com/woocommerce/woocommerce-ios/pull/13508#discussion_r1704850164) as well, since breaks the separation between `pos` and `app` by using the existing Order model rather than a specific POSOrder.

I'll open a thread in slack to share some thoughts, and we can prioritize this appropriately.

2024-08-08 05:01 UTC, iamgabrielma commented on WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleCardPresentPaymentInLineMessage.swift
> +    private let order: Order?
Question: Should this `Order` property be optional? Or is there always an Order present when the inline message is created? AFAIU we only make this nullable for convenience when creating a `#Preview`, if that's the case I think we should make it non-optional. It also adds to the subject of using a minimal POSOrder that we can mock/replicate easily without having to import Woo logic into the POS.

2024-08-08 05:02 UTC, iamgabrielma commented on WooCommerce/Classes/POS/Presentation/Card Present Payments/Reader Messages/PointOfSaleCardPresentPaymentSuccessMessageViewModel.swift
> +import struct Yosemite.Order
Same as with https://github.com/woocommerce/woocommerce-ios/pull/13528#discussion_r1708611654

2024-08-08 06:04 UTC, joshheald requested changes
I'm going to take a look at how we can avoid passing Order here, I think we can simplify the `PointOfSaleCardPresentPaymentSuccessMessageViewModel` creation to avoid it.

2024-08-08 07:43 UTC, joshheald commented
@staskus Thanks for the pairing – I've pushed up the changes we did together, but the tests still need updates. 

If you want to make it functional, that's cool too!

Ping me when it's ready for a re-review, and I'll take a look at the merits of changing to make it `message(CardPresentPaymentEventDetails)` once this is merged.

2024-08-08 07:51 UTC, staskus commented on WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleCardPresentPaymentInLineMessage.swift
> +import struct Yosemite.Order
Thanks for these observations and remind of the importance of separating pos and app. This will be moved out of the message.

2024-08-08 09:32 UTC, staskus commented
Thanks again, @joshheald! I made a slight restructuring and moved the test to TotalsViewModelTests.

2024-08-08 09:37 UTC, joshheald approved these changes
Looks great, nice one!

2024-08-08 09:53 UTC, merged