[HACK week] Adds favorite products filter
woocommerce/woocommerce-ios pull request #14001
Opened 2024-09-19 16:49 UTC by selanthiraiyan

Part of: https://github.com/woocommerce/woocommerce-ios/issues/12274

## Description

## Steps to reproduce

## Testing information

## Screenshots

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

2024-09-19 16:50 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-23 16:00 UTC, pmusolino requested changes
Thank you, Sharma, for opening this PR.

While testing it, I found two issues:

1. If I filter by favourite products and then remove one of these products from being a favourite, it will not be removed from the list until I refresh it.
2. This is less obvious. If I filter by favourite products and then add a product to favourites from another point (e.g., order detail or dashboard), the product list does not refresh with the new products until I do it manually using pull to refresh. I noticed that for status changes of a product (e.g., from published to draft), they work as expected.

My suggestion would be to add an observer on Core Data so that it can observe changes in the favourites, but I believe .

2024-09-23 16:00 UTC, pmusolino commented on RELEASE-NOTES.txt
> +- [internal] Ability to mark and filter favorite products. [https://github.com/woocommerce/woocommerce-ios/pull/14001]
It's worth mentioning that this has not been released yet, but it affects product filtering logic.

2024-09-23 16:00 UTC, pmusolino commented on WooCommerce/Classes/ViewRelated/Products/FavoriteProducts/FavoriteProductsUseCase.swift
>  struct DefaultFavoriteProductsUseCase: FavoriteProductsUseCase {
Do you believe it's worth writing some unit tests for `FavouriteProductsUseCase` or the one in `ProductSelectorViewModelTests` should be enough?

2024-09-24 10:20 UTC, selanthiraiyan commented
Thanks for the review and testing, Paolo!

> My suggestion would be to add an observer on Core Data so that it can observe changes in the favourites

We can't listen to core data to solve this issue because the favorite product IDs are stored in `AppSettingsStore` and not in core data. We don't store it in core data because the favorite logic is mobile only, and API doesn't support marking a product as a favorite. 

I will check other options to address the issues that you reported.

2024-09-25 05:53 UTC, selanthiraiyan commented on WooCommerce/Classes/ViewRelated/Products/FavoriteProducts/FavoriteProductsUseCase.swift
>  struct DefaultFavoriteProductsUseCase: FavoriteProductsUseCase {
Great catch. I added tests in a previous PR. It looks like I removed that file during a merge conflict. Added it back in https://github.com/woocommerce/woocommerce-ios/pull/14001/commits/5563db99ba20d837da27c0f2b49997d6aaf3de8a

2024-09-25 06:01 UTC, selanthiraiyan commented
Thanks for the review, @pmusolino! The PR is ready for another look.  🙇 

> While testing it, I found two issues:
> 
> 1. If I filter by favourite products and then remove one of these products from being a favourite, it will not be removed from the list until I refresh it.
> 2. This is less obvious. If I filter by favourite products and then add a product to favourites from another point (e.g., order detail or dashboard), the product list does not refresh with the new products until I do it manually using pull to refresh. I noticed that for status changes of a product (e.g., from published to draft), they work as expected.
> 
> My suggestion would be to add an observer on Core Data so that it can observe changes in the favourites, but I believe .

- To address these issues, I started reloading the products screen from view did appear after checking a few conditions https://github.com/woocommerce/woocommerce-ios/pull/14001/commits/c468a3e4aafab9e7adf5e372a2fa5787832f4b2b. 
- I decided not to add this reload for the `ProductSelectorViewModel` as the product selector screen is presented a modal and these issues won't happen there as we can't navigate to other screens before dismissing the product selector screen. 

Kindly let me know your thoughts.

2024-09-25 14:20 UTC, pmusolino approved these changes
Thanks, Sharma, for fixing them. Now everything works as expected 🎉

2024-09-26 05:47 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/225">20.6</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-26 06:06 UTC, merged