Remove a duplicate call to sync the first page of reviews
woocommerce/woocommerce-ios pull request #1818
Opened 2020-02-05 09:25 UTC by jaclync

Fixes #1812 

## Changes

- Removed a call to sync the first page of reviews when presenting Review Details from a push notification, which is also called in the following `viewModel.loadReview(for:)`

## Testing

We can test it with Wormholy!

Prerequisites: the app can receive push notifications in dev builds (p99K0U-1qz-p2 might be helpful) or already has a push notification for a new Review (like from a TestFlight build)

- Launch the app from PR branch
- Go to Settings > OTHER > Launch Wormholy debug
- Tap More > Clear to remove all logs
- Go back to "My store" tab
- Background the app
- Tap on a new Review push notification either from a new Review or a pre-existing push notification --> after a bit (sometimes it takes a few seconds), the app should open the Reviews tab and then present the Review Details. Go to Settings > OTHER > Launch Wormholy debug, filter by "reviews" and there should be only 2 requests made
  - Note: ideally only 1 request is made, but the other one is triggered by `viewWillAppear` and I didn't want to affect this behavior for now

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-02-05 15:14 UTC, pmusolino requested changes
It seems that this not solved the problem. I tested it with the app in background and with the app closed. 🤔 

When in the background, I always see two API requests. When the app is closed, I always see 3 API requests, and the review is opened two times (go to review list, open the review detail, open the same review detail).

2020-02-11 03:25 UTC, jkmassel commented
We're freezing `3.6` today, so this PR is being bumped to `3.7`. If you'd like it to ship with `3.6`, please merge it into `release/3.6` and ping me – I'll be happy to cut a new beta release.

2020-02-24 22:20 UTC, jkmassel commented
I'm freezing `3.7`, so this is being bumped to `3.8`. If you need it to be part of the `3.7` release, please re-target `release/3.7` and merge there. Once you have, please ping me that it's been merged and I'll be happy to cut a new beta release!

@jaclync – given that we've bumped this twice, should we evaluate whether it should still be open? :)

2020-03-09 20:30 UTC, jkmassel commented
I'm freezing `3.8`, so this is being bumped to `3.9`. If you need it to be part of the `3.8` release, please re-target `release/3.8` and merge there. Once you have, please ping me that it's been merged and I'll be happy to cut a new release candidate!

2020-03-16 02:49 UTC, jaclync commented
I'm closing this PR, since it'd be better to fix this properly in https://github.com/woocommerce/woocommerce-ios/issues/1735

2020-03-16 02:49 UTC, closed without merging