Product Settings: edit the Menu order
woocommerce/woocommerce-ios pull request #2189
Opened 2020-04-24 12:49 UTC by pmusolino

Resolve #2122 

## Description
This PR implements the Menu Order setting in Product Settings, part of M2.
This feature presents a text field that can accept positive and negative value. The lower the value of the number, the higher the item will be on the product list.

## Changes
- Encoded `menuOrder` in Product model
- Refactored `IntegerInputFormatter` using `NumberFormatter` and removing all the regex + tests
- Implemented the new `ProductMenuOrderViewController`
- Added the new `MenuOrder` row in `ProductSettingsRows`
- The view model of `TextFieldTableViewCell` now accept an input formatter
- Updated tests to support `menuOrder`

## Testing
1. Open a simple product
2. Open product settings
3. Tap in "Menu Order" cell
4. Try to edit the menu order value. -> Make sure that only integer values are accepted
5. Press back and save the product.
6. Go to this product from wp-admin and make sure the value was saved correctly.

## Screenshots
| Product Settings screen            |  Menu Order screen |
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-24 at 14 30 56](https://user-images.githubusercontent.com/495617/80213029-d8188e80-8638-11ea-9e61-5b44b8b44410.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-24 at 14 26 06](https://user-images.githubusercontent.com/495617/80213033-db137f00-8638-11ea-92c5-6db19bcfff81.png)

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-04-24 21:13 UTC, shiki reviewed
This is looking good, @pmusolino. I have a few suggestions and comments. 🙂 

## Questions

@Garance91540 Is this how the Product Settings is supposed to look like in Dark mode? It seems a little too dark. I can't find a reference to it in Figma. 🤔 

<img src="https://user-images.githubusercontent.com/198826/80252582-c339fc00-8634-11ea-8f9e-a137000ba6a1.png" width="320">

Should we show the number-only keyboard instead of this?

<img src="https://user-images.githubusercontent.com/198826/80252891-7d316800-8635-11ea-813b-f7ceee017c76.png" width="320">

Should we show the value of the Menu Order in here?

<img src="https://user-images.githubusercontent.com/198826/80257080-60009780-863d-11ea-8587-6d83697b6f80.png" width="320">

2020-04-24 21:13 UTC, shiki commented on WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Menu Order/ProductMenuOrderViewController.swift
> +    }
I believe this is the same as setting this in `configureTableView`:

```suggestion
        tableView.allowsSelection = false
```

2020-04-27 08:33 UTC, Garance91540 commented
👋 Thanks @shiki!

> @Garance91540 Is this how the Product Settings is supposed to look like in Dark mode? It seems a little too dark. I can't find a reference to it in Figma. 🤔

Hi @shiki ! We haven't included dark mode designs for products, we need to take this habit! But you are right, it seems like the rows' background have the same color as the screen background and they should be lighter. Let's apply similar styling to how we styled the app global Settings screen: https://d.pr/i/518inp

For reference, dark mode designs for the main screens are in the Figma file "System - Dark/Light mode"

> Should we show the number-only keyboard instead of this?

Good idea!

> Should we show the value of the Menu Order in here?

Yes, good catch!

2020-04-27 08:36 UTC, Garance91540 requested changes
👋 Thanks @shiki!

> @Garance91540 Is this how the Product Settings is supposed to look like in Dark mode? It seems a little too dark. I can't find a reference to it in Figma. 🤔

Hi @shiki ! We haven't included dark mode designs for products, we need to take this habit! But you are right, it seems like the rows' background have the same color as the screen background and they should be lighter. Let's apply similar styling to how we styled the app global Settings screen: https://d.pr/i/518inp

For reference, dark mode designs for the main screens are in the Figma file "System - Dark/Light mode"

> Should we show the number-only keyboard instead of this?

Good idea!

> Should we show the value of the Menu Order in here?

Yes, good catch!

2020-04-27 13:27 UTC, pmusolino commented
Thank you both for your reviews! @shiki @Garance91540 

I'll update the design in dark mode. Good catch!

> Should we show the number-only keyboard instead of this?

Unfortunately, Apple does not allow us to have a keyboard-only number where there is a minus sign, and here it is essential to be able to add the sign. That seems to be the only Apple keyboard that allows us to have the minus sign and numbers in evidence.

> Should we show the value of the Menu Order in here?

I'll update it 👍

2020-04-27 13:37 UTC, pmusolino commented on WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift
> +        onTextChange?(formattedText)
I updated it, this should be more understandable. What do you think?
```
    @objc func textFieldDidChange(textField: UITextField) {
        guard let formattedText = viewModel?.inputFormatter?.format(input: textField.text) else {
            onTextChange?(textField.text)
            return
        }
        textField.text = formattedText
        onTextChange?(formattedText)
    }
```

2020-04-27 13:49 UTC, pmusolino commented on WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Menu Order/ProductMenuOrderViewController.swift
> +        onCompletion(productSettings)
Thanks for clarifying this aspect @shiki! I updated the code, and probably I'll open a new PR to update it also on other points of Product Settings.

2020-04-27 13:54 UTC, shiki commented on WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift
> +        onTextChange?(formattedText)
That works too! 👏

2020-04-27 13:58 UTC, pmusolino commented on WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Menu Order/ProductMenuOrderViewController.swift
> +        cell.textField.keyboardType = .numbersAndPunctuation
I agree but it seems that we started to use the `textField` property in a lot of points of the app to edit the style. I think I'll open a new PR to handle this change. Issue: https://github.com/woocommerce/woocommerce-ios/issues/2196

2020-04-27 14:01 UTC, pmusolino commented on WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Menu Order/ProductMenuOrderViewController.swift
> +    }
Good suggestion. This can be improved also in other view controllers.

2020-04-27 16:06 UTC, shiki reviewed
Looking good, @pmusolino!  

✔️ Dark mode
✔️ Menu Order number
✔️ Code changes

> Unfortunately, Apple does not allow us to have a keyboard-only number where there is a minus sign, and here it is essential to be able to add the sign. That seems to be the only Apple keyboard that allows us to have the minus sign and numbers in evidence.

Oh, good point about the negative value. 

It doesn't seem to be possible to set a negative value right now though. In [this video](https://drive.google.com/file/d/13Jm1cldjkZjF20GOf1iXKU5FnkAHylkP/view?usp=sharing), you'll see me trying to change a menu order that was previously a negative value. I couldn't seem to keep the negative value at all. 

Do you think this should be fixed in this PR? Or a different PR? Let me know.

2020-04-28 09:23 UTC, pmusolino commented
Good catch @shiki! I'll open a new PR for this issue https://github.com/woocommerce/woocommerce-ios/issues/2205

2020-04-28 11:42 UTC, shiki approved these changes
🤸

2020-04-29 07:42 UTC, Garance91540 approved these changes
👏

2020-04-29 09:19 UTC, merged