Hide WordPress.com TOS
woocommerce/woocommerce-ios pull request #3301
Opened 2020-12-08 03:28 UTC by ctarda

Closes #3145 
Ref: wordpress-mobile/WordPressAuthenticator-iOS#536

## Changes

| Before | After |
| ---- | ---- |
| <img src="https://user-images.githubusercontent.com/2722505/101435919-23717a00-3948-11eb-8199-32951ac94596.png" width="350"/> | <img src="https://user-images.githubusercontent.com/2722505/101435911-1fddf300-3948-11eb-8339-948b6f4365ac.png" width="350"/> |

* Point the podfile to the branch in WPAuthenticator that actually implements the solution
* Update AuthenticationManager to implement the new delegate method that allows removing the link to the TOS

## Testing
* Checkout the branch, run `bundle exec pod install`
* Log out if necessary
* Attempt to log in with a WordPress.com account. Notice if the link to the Terms Of Service worth above the "Continue" button is visible.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-12-08 08:33 UTC, jaclync approved these changes
LGTM! 🚢 

before | after
-- | --
![Simulator Screen Shot - iPhone 8 Plus - 2020-12-08 at 16 31 26](https://user-images.githubusercontent.com/1945542/101459287-056d3f00-3973-11eb-923c-53693c3bfa96.png) | ![Simulator Screen Shot - iPhone 8 Plus - 2020-12-08 at 16 32 29](https://user-images.githubusercontent.com/1945542/101459303-0900c600-3973-11eb-8813-b25efb68a8f1.png)

2020-12-08 09:55 UTC, Garance91540 requested changes
Hi Cesar, can we make sure there's 16px vertical padding between the email text field and the "Continue" button? https://d.pr/i/smfi7B

2020-12-08 10:18 UTC, ctarda commented
Hi @Garance91540 , thanks for the review!

I am afraid we can't, at least not without significant effort, as that UI is provided by WPAuthenticator and we don't have much control over it, other than hiding the TOS. 

How critical would you say that is? If it is, is this something we could defer to a second milestone?

2020-12-08 13:03 UTC, Garance91540 commented
> How critical would you say that is? If it is, is this something we could defer to a second milestone?

This is purely visual, so it's fine to defer for later!

2020-12-09 01:25 UTC, ctarda commented
> This is purely visual, so it's fine to defer for later!

Thanks! I've logged #3309 for that. Merging now!

2020-12-09 01:25 UTC, merged