Don't dismiss order details if order is temporarily deleted during sync
woocommerce/woocommerce-ios pull request #3359
Opened 2020-12-16 14:20 UTC by eshurakov

Closes #2369 

The issue is that the app shows an "Order has been deleted from your store" notice and pops the view controller even though the order was not really deleted from the store. It happens when we sync orders. Orders are temporarily removed from the database.

In this PR I'm trying to workaround this by using a timer to delay processing the fact that order is deleted. If the order is deleted during sync process, we should get a callback from the `EntityListener` with an updated order and can safely invalidate the timer. If we didn't get any callback and timer is fired, we can consider the order being truly deleted and show a notice and pop the view controller.

What do you think of this approach?

## Tests

You can follow a steps to reproduce from #2369 or update `fetchFilteredAndAllOrders` method in `OrderStore` and change 
`serialQueue.async { [weak self] in` 
to 
`serialQueue.asyncAfter(deadline: .now() + 3.0) { [weak self] in`

Scenario 1.

1. Navigate to Orders
2. Pull to refresh
3. Pick any Order
4. Verify that Order is not dismissed and "Order has been deleted from your store" notice is not shown (wait for a few seconds)

Scenario 2.

1. Navigate to Orders
2. Wait till sync is finished
3. Delete one of the orders in Core
4. Pull to refresh
5. Open the order from step 3
6. Verify that Order is dismissed and "Order has been deleted from your store" notice is shown (wait for a few seconds)

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-12-16 20:48 UTC, shiki requested changes
Hi @eshurakov! Thanks for looking into this. 

I'm sorry I didn't clarify the issue more. I think we should just remove the `onDelete` handling altogether. It causes more problems than it's worth. It's confusing and scary to merchants if they come up. If a merchant has deleted an order, **they would know** anyway and they don't need to be reminded of it.

Android also doesn't have a mechanism like this and just lets the Order page remain visible. The merchant will not be able to do anything anyway if it's permanently deleted. If it's just Trashed, then they can still interact with the UI, and that behavior still makes sense. 

We also removed this similar behavior in Reviews because it was also causing issues, not just in sync but even in push notifications. Please see this commit https://github.com/woocommerce/woocommerce-ios/commit/e59a5265e5468b673df997b884e8942359a5fc57.

2020-12-17 08:28 UTC, eshurakov commented
Thank you @shiki! 
I have updated my PR with the suggested approach. I found that we also had a similar `onDelete` handling in `RefundedProductsViewController` and removed it from there as well.

2020-12-17 14:45 UTC, shiki approved these changes
Tested and works great! Thank you for being thorough! 🙏 

:shipit:

2020-12-18 09:00 UTC, eshurakov commented
Thank you for the review @shiki, merging it 👍

2020-12-18 09:00 UTC, merged