Design enhancement for "Reprint Shipping Label" CTA: hide separator and remove bottom spacing
woocommerce/woocommerce-ios pull request #3430
Opened 2021-01-06 07:24 UTC by jaclync

Part of #3334 

## Why

According to design, there is no separator and only ~10px spacing between the bottom of "Reprint Shipping Label" CTA and the top of  "Don’t know how to print from your phone?" info row.

<img width="300" alt="Screen Shot 2021-01-06 at 3 15 41 PM" src="https://user-images.githubusercontent.com/1945542/103740507-4e77e800-5032-11eb-97e8-b78aed739440.png">

In our table view implementation, "Reprint Shipping Label" CTA and  "Don’t know how to print from your phone?" info row are two separate table view cells with their own vertical spacing within the cell. In order to achieve the design specs, this PR updates the "Reprint Shipping Label" CTA row (`ButtonTableViewCell`):

- Hides the separator (and calls `showSeparator` for another `ButtonTableViewCell` use case for "Begin Fulfillment" CTA in order details)
- Removes the bottom spacing (the top and bottom constraints in `ButtonTableViewCell.xib` are updated to 20px to the superview instead of 8px to layout margins, otherwise we can't completely remove the bottom spacing)

## Testing

Please check the affected use cases:

- Orders tab > order with at least one non-refunded shipping label --> "Reprint Shipping Label" CTA and  "Don’t know how to print from your phone?" should look as design
- Orders tab > order that can be fulfilled --> "Begin Fulfillment" CTA should look as before
- Products tab > edit product > edit linked products --> the button cells should look as before

## Example screenshots

screen | before | after
-- | -- | --
Order details > Reprint Shipping Label CTA --> there is no separator and bottom spacing anymore | ![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 14 56 23](https://user-images.githubusercontent.com/1945542/103739833-2a67d700-5031-11eb-822a-08d919c3b89e.png) | ![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 14 59 52](https://user-images.githubusercontent.com/1945542/103739835-2b990400-5031-11eb-9a7f-634ab7d1431d.png)
Order details > Begin Fulfillment CTA | ![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 15 12 38](https://user-images.githubusercontent.com/1945542/103740128-a82be280-5031-11eb-8459-5b1bd17545ae.png) | ![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 14 59 59](https://user-images.githubusercontent.com/1945542/103739908-48353c00-5031-11eb-95ae-1ca340fe603d.png)
Edit product > linked products | ![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 14 54 04](https://user-images.githubusercontent.com/1945542/103740184-c1cd2a00-5031-11eb-90ad-5ed395d16298.png) | ![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 14 58 45](https://user-images.githubusercontent.com/1945542/103740192-c42f8400-5031-11eb-8589-f79940ee134d.png)

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-01-06 09:01 UTC, Garance91540 requested changes
Hi @jaclync ! hiding the separator looks good. But looking at your screenshot https://d.pr/i/UHsqci I think the tap area is too small and we are going to see fat fingers issues. Is it possible to add 8px of vertical padding bottom and top to "don't know how to print from your phone"? Thank you!

2021-01-06 09:24 UTC, jaclync commented
Hey @Garance91540! How does this look after adding 8px to the bottom of the CTA:

normal | info row tapped
-- | --
![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 17 22 25](https://user-images.githubusercontent.com/1945542/103751875-e9c58900-5043-11eb-9588-5328937b3a8b.png) | ![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 17 23 12](https://user-images.githubusercontent.com/1945542/103751886-ecc07980-5043-11eb-820e-93290f234ea4.png)

2021-01-06 12:59 UTC, Garance91540 commented
Hi @jaclync definitely better! Can we add 8px more under "Don't know how to print from your phone" too?

2021-01-06 15:07 UTC, Ecarrion approved these changes
Code and test look good to me!

2021-01-07 01:16 UTC, jaclync commented
> Can we add 8px more under "Don't know how to print from your phone" too?

@Garance91540 could you pinpoint where this 8px shall be added, like below or above the separator of the "Don't know how to print from your phone" row? If it's above the separator, it might make the [highlighted state](https://user-images.githubusercontent.com/1945542/103751886-ecc07980-5043-11eb-820e-93290f234ea4.png) uneven in the vertical space.

2021-01-07 01:50 UTC, adamzelinski commented
Hey, @jaclync it looks like the padding needs to be added under "Don't know how to print from your phone", please. The designs that I have also don't show the separator below the label so could we please hide this too.

<img width="873" alt="Screen Shot 2021-01-07 at 11 36 06 am" src="https://user-images.githubusercontent.com/74938219/103840965-57be8e80-50de-11eb-9fec-e56b35b25b4b.png">

2021-01-07 02:12 UTC, jaclync commented
Hi @woocommerce/mobile-designers thanks for the feedback! Since this PR is already code reviewed and aims to update the design for "Reprint Shipping Label" CTA, I just added another subtask to #3334 for the "Don't know how to print from your phone" design changes and will work on them separately.

Hiding the separator is a bit tricky right now since the "Don't know how to print from your phone" row type is reused by 3 other rows that have an image/title in order details. It requires a bit more work to show/hide the separator for this cell type, so I'm merging this PR now and another PR will follow soon!

2021-01-07 02:12 UTC, merged