Fix for #3551
woocommerce/woocommerce-ios pull request #3553
Opened 2021-02-01 17:33 UTC by CrazyBusyCreative

Did a s/'Enter the address of *your* WooCommerce store'/Enter the address of *the* WooCommerce store/

FYI - I changed the English versions of the localization strings, but didn't touch the translations.

Update release notes:
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-02-01 22:14 UTC, CrazyBusyCreative commented
The failed ci tests had to do with my local environment - they are fixed now, but CI won't let me rerun the tests

2021-02-04 16:31 UTC, shiki requested changes
Hi, @CrazyBusyCreative! I'm so sorry for the delay! Thank you for contributing! 

There is no need to edit the `Localizable.strings` files. I'm sorry we haven't documented that. We can use the documentation in WordPress for now. From [the Localization doc](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/docs/localization.md):

> During development, using NSLocalizedString() in the code should be enough. You shouldn't need to touch the Localizable.strings files manually.
> 
> During the release process, NSLocalizedString statements are scanned and stored in the Localizable.strings file. The file is then uploaded to GlotPress for translation. Before the release build is finalized, all the translations are grabbed from GlotPress and saved back to the Localizable.strings files.

Would you mind changing this and just leaving the `AuthenticationConstants` change? And then we can let the translators deal with the changes for `Localizable.strings`. 🙂

2021-02-22 12:33 UTC, AliSoftware commented
Hi there! I'm code-freezing the version 6.1 so that we start beta-testing on it. So I updated the milestone of this PR to 6.2.
_Don't hesitate to ping me if you feel this PR needs to make it to 6.1 anyway and we could retarget it if needed._

2021-03-05 23:20 UTC, shiki commented
Looks like this PR has stalled. Going to close this for now.

2021-03-05 23:20 UTC, closed without merging