[Mobile Payments] Add support for metadata to PaymentIntentParameters. Add an extra layer of validation to the parameters passed to the Stripe Terminal SDK
woocommerce/woocommerce-ios pull request #3879
Opened 2021-03-26 16:41 UTC by ctarda

Closes #3877 and #3835

⚠️ This PR is against the feature branch implementing support for Card Present Payments, not against develop ⚠️

The integration with the Stripe Terminal SDK provides a way to create Payment Intents on device. In order to create a Payment Intent we need to provide an instance of a class ([SCPaymentIntent](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPPaymentIntentParameters.html)) that wraps a set of parameters. 

The Stripe Terminal SDK imposes certain constrains on some of those parameters, for example:
* [Currency](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPPaymentIntentParameters.html#/c:objc(cs)SCPPaymentIntentParameters(py)currency) must be lowercase and meet the ISO standard
* The [descriptor that will shown in statements](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPPaymentIntentParameters.html#/c:objc(cs)SCPPaymentIntentParameters(py)statementDescriptor) cannot contain certain characters and must be of a certain length.
* The [email](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPPaymentIntentParameters.html#/c:objc(cs)SCPPaymentIntentParameters(py)receiptEmail) passed to generate a receipt must be a valid email address

Passing data that does not comply to those restrictions will make the creation of a PaymentIntent fail. 

So this PR does not completely solve the problem of data validation, which will need to be performed on the UI anyway (for example, validating that an email address provided by the user is valid) but adds one more extra layer of protection.

In other words, this might not be technically needed, and we surely should not rely on validating data this low in the stack, but I guess it does not hurt to have some extra protection. And property wrappers are fun.

## Changes
* Add support for a metadata dictionary. This might be needed to pass some extra data like a zip code.
* Add three property wrappers: one that validates an email address, another one that forces a string to be lowercase, and a third one that removes a set of characters and trims a string.
* Add some tests

## Testing.
* There are no user facing changes, so 👀  on the code and waiting for CI to ✅ could be enough.
* Processing a payment would not hurt. For instructions on how to process a payment, see #3847 

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-03-26 18:46 UTC, allendav commented on Hardware/Hardware/CardReader/Lowercase.swift
> +@propertyWrapper
Could we use https://developer.apple.com/documentation/foundation/nslocale/1417834-isocurrencycodes ?

2021-03-26 18:50 UTC, allendav commented on Hardware/Hardware/CardReader/StatementDescriptor.swift
> +@propertyWrapper
On the web side, we found it useful to trim leading (or trailing) spaces too - for some reason people would enter those and then the descriptor string would get truncated in unexpected ways

2021-03-26 18:58 UTC, allendav commented on Hardware/Hardware/CardReader/Email.swift
> +        let emailRegEx = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}"
Maybe add comment pointing at http://emailregex.com/

2021-03-26 19:09 UTC, allendav requested changes
A couple of suggested changes. PaymentIntentParametersTests pass.

2021-04-06 11:35 UTC, ctarda commented
Thanks for the review @allendav . This is ready for another round:
* I renamed Lowercase.swift to CurrencyCode.Swift, which seems to reflect the intent better
* The conversion to the corresponding Stripe model object will fail now if the currency code is not declared in Locale.isoCurrencyCodes
* And the service will emit an error in that case as well.

2021-04-07 21:57 UTC, allendav approved these changes
Thank you for making the changes. All the tests under `PaymentIntentParametersTests` pass.

:shipit:

2021-04-07 22:12 UTC, ctarda commented
Thanks for following up @allendav 🙇  Merging now!

2021-04-07 22:13 UTC, merged