[Mobile Payments] Update background colour of modal alerts
woocommerce/woocommerce-ios pull request #4367
Opened 2021-06-03 18:58 UTC by ctarda

Closes #4358 

The Cancel button will be tackled in a separate ticket: #4364

| Before | After |
| ---- | ---- |
| <img src="https://user-images.githubusercontent.com/2722505/120697732-15765f00-c47c-11eb-99f1-42a7ab14ef4d.png" width="350"/> | <img src="https://user-images.githubusercontent.com/2722505/120697747-18714f80-c47c-11eb-814b-bdb701b7c432.png" width="350"/> |

Update release notes:
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-03 22:48 UTC, allendav commented
@ctarda I took the liberty of merging develop into this branch to pick up the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` change

2021-06-03 23:03 UTC, allendav approved these changes
Tests fine. I did note that on iPad the background color of the presenting view controller in dark mode isn't quite right, so I opened a separate issue for that in https://github.com/woocommerce/woocommerce-ios/issues/4374

![IMG_0063](https://user-images.githubusercontent.com/1595739/120722757-31323300-c485-11eb-8e4e-dca71ff311cd.PNG)
![IMG_0065](https://user-images.githubusercontent.com/1595739/120722760-32636000-c485-11eb-96d5-c2e13b622e63.PNG)

2021-06-04 03:48 UTC, adamzelinski requested changes
This looks great @ctarda just one small change request, please. The padding of the text to the sides of the modal looks a little tight to me. Do you mind adding a little more. I'm not sure what it's set at but the mobile ones use 20px.

<img width="1363" alt="Screen Shot 2021-06-04 at 1 47 14 pm" src="https://user-images.githubusercontent.com/74938219/120743030-8761ad80-c53b-11eb-83cd-9755362095b3.png">

2021-06-04 15:28 UTC, ctarda commented
Good catch @adamzelinski 

I just pushed an update that increments the leading and trailing margins to 20px (it as set at 16)

| Before | After |
| ---- | ---- |
| <img src="https://user-images.githubusercontent.com/74938219/120743030-8761ad80-c53b-11eb-83cd-9755362095b3.png" width="350"/> | <img src="https://user-images.githubusercontent.com/2722505/120826023-01883700-c528-11eb-8dfd-83cd11881f68.png" width="350"/> |

2021-06-07 03:37 UTC, adamzelinski approved these changes

2021-06-07 15:59 UTC, merged