[Mobile Payments] Apply headline style to title in all modals
woocommerce/woocommerce-ios pull request #4368
Opened 2021-06-03 19:08 UTC by ctarda

Closes #4331 

The cancel button will be tackled in #4364 

The fix is applied to al modals. To illustrate the change, I added just two screenshots.

| Before | After |
| ---- | ---- |
| <img src="https://user-images.githubusercontent.com/2722505/120698605-43a86e80-c47d-11eb-9124-c6fec8fd9414.png" width="350"/> | <img src="https://user-images.githubusercontent.com/2722505/120698607-44410500-c47d-11eb-8401-49e81ead597a.png" width="350"/> | 
| <img src="https://user-images.githubusercontent.com/2722505/120698642-4f943080-c47d-11eb-861d-3bf82414f6ae.png" width="350"/> | <img src="https://user-images.githubusercontent.com/2722505/120698644-4f943080-c47d-11eb-88e3-783c268288ee.png" width="350"/> | 

## Changes
* Apply headline style to modal title

## How to test
* Navigate to any part of the payment process that displays a modal (for example, connecting to a reader). Notice the style of the primary title

Update release notes:
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-03 23:31 UTC, allendav commented
@ctarda I took the liberty of merging develop into this branch to pick up the ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES change

2021-06-03 23:34 UTC, allendav approved these changes
Tests fine. :shipit: 

![IMG_0069](https://user-images.githubusercontent.com/1595739/120724903-9ab44080-c489-11eb-8d0b-ad009a710ccd.PNG)

![IMG_0070](https://user-images.githubusercontent.com/1595739/120724932-a9025c80-c489-11eb-9f6e-dae01961d0f1.PNG)

2021-06-04 10:02 UTC, Garance91540 requested changes
Thanks for including some iPad screenshots too! I noticed that the text in the iPad modal seems a bit crowded Could we adjust left and right padding to 32px? (so the text will be wrapped up on 2 lines?) https://d.pr/i/IdtCTj

Small request: is it possible to only make the reader name bold in this modal? https://d.pr/i/TiogDQ

Everything else looks great, thank you for tackling so quickly!

2021-06-04 13:56 UTC, ctarda commented
> Small request: is it possible to only make the reader name bold in this modal? https://d.pr/i/TiogDQ
@Garance91540  That turns out to be a bit complicated. Can we defer that to a separate ticket?

2021-06-07 07:28 UTC, Garance91540 commented
yes!

2021-06-07 16:01 UTC, ctarda commented
Thanks @Garance91540  Can I merge for now, then, if we defer the title to later? It looks like it was your only request for change 😊

2021-06-07 16:42 UTC, Garance91540 approved these changes
Ah yes sorry I just saw your comment but didnt realize I was a reviewer

2021-06-08 11:19 UTC, merged