Hack Week: improve the loading state in the Order Detail
woocommerce/woocommerce-ios pull request #4396
Opened 2021-06-10 12:44 UTC by pmusolino

As discussed here p91TBi-5f1, we'd like to improve the loading state of the Order Detail screen.
So, I implemented the solution proposed by @Garance91540 here: p91TBi-5f1#comment-4949.

One of the main issues that we want to solve, is to communicate to our users, displaying a refresh control on top of the table view, that the screen is still loading its content.

## Testing
#### Case 1
1. Open an Order Detail.
2. You should see the detail of the order, and an activity indicator on top (the same we use for the pull to refresh action).
3. The activity indicator should be hidden when all the requests finish.
4. The pull to refresh action should work like before.
5. If you try to open a sub-screen starting from Order Detail when you do a "pop" action, you should see the indicator at the top again.

#### Case 2
1. Open an Order Detail.
2. Open a sub-screen starting from Order Detail (like tapping "View Billing Information") 
3. Tap back.
4. You should see the indicator at the top again, while we are refreshing the data.

## Video

https://user-images.githubusercontent.com/495617/121526997-3bf74580-c9fa-11eb-80df-62cd1830a20f.mp4

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-10 18:05 UTC, allendav commented on WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
> +        refreshControl.beginRefreshing()
Do we need to be concerned if the user pulls to refresh while a programmatic refresh is happening?

2021-06-10 18:06 UTC, allendav commented
@ctarda - it would be nice to trigger this after collecting a payment - what do you think?

2021-06-10 18:23 UTC, Garance91540 requested changes
Ah Paolo I misunderstood when you asked if we should use the same indicator! I still want us to display the banner, but I just thought you wanted to use this indicator instead of the one I used in my designs. https://d.pr/i/bBX0gR

As pull to refresh and loading are different (although close) actions, I don't think they should be displayed the same way. (The banner appears as the page is loading automatically vs the spinner appears when you trigger a refresh).

2021-06-10 18:33 UTC, allendav approved these changes
Tests nicely. One question about simultaneous manual and programatic refreshes. (Which I tried but it didn't seem to be a problem nor precipitate an error.)

![IMG_0074](https://user-images.githubusercontent.com/1595739/121578485-91722900-c9df-11eb-9239-2fccb3706d89.PNG)

2021-06-11 08:22 UTC, pmusolino commented
Thank you both @allendav and @Garance91540. I'll update the design using the suggestion of Garance.
@Garance91540 do you think that in the case of dark mode enabled, we should use the white background for the banner and the black for the text?

2021-06-11 15:03 UTC, pmusolino commented
I updated the design, implementing the top loader view as suggested by @Garance91540, which can be used as a banner and that is embedded inside a stack view where we embed also the table view. 

Can you re-check it, please? @Garance91540 @allendav 🙇 

## Screenshots
| Light Mode            |  Dark Mode |
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 12 Pro - 2021-06-11 at 16 46 28](https://user-images.githubusercontent.com/495617/121707278-b09fb200-cad6-11eb-98d6-577d9a378ea8.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-11 at 16 46 42](https://user-images.githubusercontent.com/495617/121707519-ee043f80-cad6-11eb-9e42-e5f3164d71d2.png)



## Video
https://user-images.githubusercontent.com/495617/121707239-a7164a00-cad6-11eb-8a9c-8011cf011737.mp4

2021-06-11 16:06 UTC, Garance91540 approved these changes
Looking neat!

2021-06-11 16:09 UTC, Garance91540 commented
Now that we created this component, I wonder if we can generalize its usage to any update that happens after screens have been loaded, for example for actions that happen on the web and update the app automatically. One that I have in mind that I think Jirka or Allen brought up is this one: 

https://cloudup.com/c1LrT9DG-6b

If I'm on the Order List and I receive an order, the new order will pop out automatically, but I have no feedback that this just happened. Could we add the banner in this instances?

2021-06-14 07:24 UTC, pmusolino commented
@Garance91540 In the order list, we update the content every time the user navigates between different screens (since we have no way, at the moment, to understand if there are new orders compared to those previously downloaded). In that case, we would show the loader every time that screen loads.

2021-06-14 09:42 UTC, ctarda commented
I just wanted to drop a drive-by comment... This is great work and a significant improvement @pmusolino . Thanks for doing this.

2021-06-14 19:11 UTC, allendav approved these changes
Tests fine. I confirmed the pull-to-refresh is as it always has been (a spinner) and the initial load now looks like:

![IMG_0077](https://user-images.githubusercontent.com/1595739/121946102-6c482800-cd09-11eb-8079-a70718829ff0.png)

![IMG_0076](https://user-images.githubusercontent.com/1595739/121946107-6f431880-cd09-11eb-9a5d-f3f0d2e10051.PNG)

![IMG_0078](https://user-images.githubusercontent.com/1595739/121946335-add8d300-cd09-11eb-8eb5-2804eeb03137.png)

![IMG_0079](https://user-images.githubusercontent.com/1595739/121946342-ae716980-cd09-11eb-941f-0141a0feddf8.PNG)

2021-06-14 22:45 UTC, merged