[Mobile Payments] Unbreak modals in landscape just a tad
woocommerce/woocommerce-ios pull request #4479
Opened 2021-06-24 20:59 UTC by ctarda

Closes #4474 

Update release notes:
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-25 01:00 UTC, allendav commented
Tested on iPad (10.2") and iPhone XR. Some button labels were cut off, and some images missing or scaled very small

iPhone

![iPhone5](https://user-images.githubusercontent.com/1595739/123353276-097b3b80-d516-11eb-9abd-e6e5a6c27a6c.PNG)
![iPhone4](https://user-images.githubusercontent.com/1595739/123353278-0b44ff00-d516-11eb-992f-6c1d44e74d5a.PNG)
![iPhone3](https://user-images.githubusercontent.com/1595739/123353279-0bdd9580-d516-11eb-9edb-9ee16efaf84c.PNG)
![iPhone2](https://user-images.githubusercontent.com/1595739/123353281-0c762c00-d516-11eb-8e83-43c0df72d0b3.PNG)
![iPhone1](https://user-images.githubusercontent.com/1595739/123353282-0d0ec280-d516-11eb-9367-82e4a6067755.PNG)

iPad

![iPad3](https://user-images.githubusercontent.com/1595739/123353284-0d0ec280-d516-11eb-915f-9a20e36ae3f4.PNG)
![iPad2](https://user-images.githubusercontent.com/1595739/123353285-0da75900-d516-11eb-93a1-3974af3dfcd3.PNG)
![iPad1](https://user-images.githubusercontent.com/1595739/123353289-0e3fef80-d516-11eb-9b02-0b53c0f5c848.PNG)

2021-06-28 07:48 UTC, adamzelinski commented
I think having 3 columns in the landscape modals could cause a few problems down the road and it looks like there will be problems with text and button cutoffs. Hiding the illustrations might be the way to go for these. I put together a quick concept where we could have 2 buttons full width and then the 3rd action below. Also option for having the illustration or without. Let me know your thoughts @ctarda @allendav @Garance91540 

<img width="1824" alt="Screen Shot 2021-06-28 at 5 45 47 pm" src="https://user-images.githubusercontent.com/74938219/123599435-ef549c80-d838-11eb-8077-734cbbe2a139.png">

2021-06-28 20:22 UTC, ctarda commented
@adamzelinski How would you visualize the error messages in landscape mode?

Error messages might contain, from top to bottom, two lines of text, an illustration, an error message (that will most likely span across two lines) and one or two buttons. An example in portrait mode could be this:

<img src="https://user-images.githubusercontent.com/2722505/123699144-ebbb1880-d82c-11eb-88ab-75a7dfa0fc10.png" width="350"/>

2021-06-29 06:19 UTC, adamzelinski commented
@ctarda I think something like this would work

<img width="1512" alt="Screen Shot 2021-06-29 at 4 18 32 pm" src="https://user-images.githubusercontent.com/74938219/123747073-c5ad7b00-d8f5-11eb-8b55-fc2d279bf3ed.png">

2021-06-29 12:50 UTC, Garance91540 commented
Hi everyone! Aaaah landscape mode, always a tough one 😅. Since we are losing a significant amount of real estate in that mode, I think less is more here. 

Removing the illustration on landscape mode is my preferred option:  

<img width="267" alt="Screen Shot 2021-06-29 at 2 48 39 PM" src="https://user-images.githubusercontent.com/28450084/123800177-4d40bd00-d8e9-11eb-953c-4ee517485347.png">

2021-06-29 12:51 UTC, Garance91540 requested changes
Yes it's a bit dry, but I think it keeps the information displayed clear and prevents any confusion

2021-07-05 10:19 UTC, ctarda commented
Closing for now.

2021-07-05 10:19 UTC, closed without merging