[Mobile Payments] Use "cancel style" for secondary modal buttons
woocommerce/woocommerce-ios pull request #4552
Opened 2021-07-06 09:50 UTC by koke

Fixes #4507 

The secondary button in the payment modals was showing the wrong colors while pressed:

Normal | Highlighted
-|-
![IMG_DBF20042A5B5-1](https://user-images.githubusercontent.com/8739/124579788-c1321680-de4f-11eb-9ca1-31aab4b30f68.jpeg)|![IMG_6391](https://user-images.githubusercontent.com/8739/124579811-c5f6ca80-de4f-11eb-9766-faf35dfca6f7.PNG)

I started trying to fix the background, but then I realized that the designs didn't have this kind of borderless button, so I switched it to the alternate "ModalCancelButtonStyle".

## Screenshots (when pressed)

Before:

Light|Dark
-|-
![IMG_6391](https://user-images.githubusercontent.com/8739/124580000-f76f9600-de4f-11eb-8383-d887dccb2e5c.PNG)|![IMG_6392](https://user-images.githubusercontent.com/8739/124580011-f9395980-de4f-11eb-98d9-f776efb56987.PNG)

After:

Light|Dark
-|-
![IMG_0004](https://user-images.githubusercontent.com/8739/124580057-05251b80-de50-11eb-9880-48cae98ec048.PNG)|![IMG_0005](https://user-images.githubusercontent.com/8739/124580065-06eedf00-de50-11eb-9f81-7ee4bab3a7e8.PNG)

## To test

This is used in several modals, but the easiest one to test:

1. Go to Settings > Manage Card Reader
2. Tap on Connect Card Reader
3. Turn on the reader and wait for the alert to show it's avaiable
4. Press and old Keep Searching

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-07-06 10:32 UTC, ctarda approved these changes
Some screenshots while the button is being tapped:

<img src="https://user-images.githubusercontent.com/2722505/124585889-c37e7b80-de23-11eb-9cee-4974cb1ba3e8.png" width="350"/>
<img src="https://user-images.githubusercontent.com/2722505/124585890-c37e7b80-de23-11eb-89f1-97617be295e7.png" width="350"/>
<img src="https://user-images.githubusercontent.com/2722505/124585891-c37e7b80-de23-11eb-8e8d-0c5c8ea67cd4.png" width="350"/>

:shipit:

2021-07-07 03:18 UTC, adamzelinski requested changes
@koke @ctarda all of these look great thanks. However, for the text buttons, I think we should just lower the opacity when it's pressed. Could we try 50%, please

<img width="970" alt="Screen Shot 2021-07-07 at 1 16 35 pm" src="https://user-images.githubusercontent.com/74938219/124695045-cbbedf80-df25-11eb-8341-f95642c4c5cd.png">

2021-07-07 06:53 UTC, koke commented
> for the text buttons

@adamzelinski I didn't see the text buttons in the Figma file, so I changed them to have a border. Is there a newer design that I missed? Can you confirm if we want those to be borderless?

![Screen Shot 2021-07-07 at 08 52 32](https://user-images.githubusercontent.com/8739/124713327-b1bed600-df00-11eb-853a-daaffa3e7c3d.png)

2021-07-07 07:25 UTC, adamzelinski commented
> I didn't see the text buttons in the Figma file, so I changed them to have a border. Is there a newer design that I missed? Can you confirm if we want those to be borderless?

Let's keep them with the border thanks @koke

2021-07-08 06:17 UTC, adamzelinski approved these changes

2021-07-08 06:17 UTC, merged