Shipping Labels: Complete validation for customs form
woocommerce/woocommerce-ios pull request #4829
Opened 2021-08-19 03:54 UTC by itsmeichigo

Part of #4687 

# Description
This PR aims to complete validation of customs form with two parts:
- Update validation for ITN field by observing changes of total values and HS tariff numbers of all the items declared in the form.
- Add validation states for each item and form, so that the main customs form list can decide whether to enable Done button.

# Changes
1. Item details view model
- Added new `@Published` variables for validated tariff number and total value of the item. These will be observed by the parent form to check which tariff number's value exceed $2,500 and requires ITN.
- Added property observers for `value` and `hsTariffNumber` to update the validated total value and tariff number.
- Added new `@Published` variable `validItem` to let parent form know if all the fields in the item details are valid or not.
- Added private method helpers for validation, which are reused between calculated variables and overall validation check.

2. Customs form input view model
- Added new `@Published` variable for `validForm` to let parent list know if all the fields as well as items in the form are valid.
- Observe all item view models' `validItem` to save the validation states for all items. These states are used to validate the form.
- Observe all item view models' `validatedHSTariffNumber` and `validatedTotalValue` and save them to configure a list of tariff numbers that require ITN.
- Added private method helpers for validation, which are reused between calculated variables and overall validation check.

3. Customs form list view model
- Observe validation states of all child forms and save them locally.
- Configured Done button to enable only when all child forms are valid.
- Configured validated form list by fetching validated form from all input view models.

4. Customs form list UI
- Return the validated form list when Done button is tapped.
- Disable Done button when it should not be enabled

5. Update unit tests for view models.

# Demo

# Testing steps
1. 

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-08-19 21:15 UTC, rachelmcr commented
I haven't finished reviewing the code yet, but I noticed a scenario where the validation isn't working as expected:

**Editing an item's tariff number without editing the value**
1. Start with an order where the order includes more than $2,500 value of an item. (For example, I tested with an order of 30 sunglasses valued at $90 per item, so the value of the sunglasses in the order was $2,700.)
2. In the custom form, open the item details and notice that all of the information is correct except the item doesn't have an HS Tariff Number.
3. Enter a tariff number for the item. At this point, I expect the ITN validation error to appear, but it doesn't.
4. Now, edit the item value and notice the ITN validation error appears.


https://user-images.githubusercontent.com/8658164/130145224-6581d015-6a8f-4349-af88-fcf7dc7e52e6.mp4

2021-08-19 22:49 UTC, rachelmcr requested changes
Apologies for not having specific comments about the code in this review! I found a couple issues (reported in my comment above) in the validation, but perhaps because I'm new to Combine I can't work out where the problem stems from.

It's a little tricky to follow how everything is connected, especially between the two view models, but for the most part the validation is working for each part of the form and each piece of the validation is documented clearly. I also confirmed that (aside from the two scenarios outlined above) the validation used for enabling the Done button also works great. 👍 

It might be worth having a second reviewer who is more familiar with Combine take a look, too, but I can certainly review/test again when you're ready.

2021-08-20 02:06 UTC, itsmeichigo commented
@rachelmcr Thank you for catching that issue about the ITN validation!

The issue was that I used property observer `didSet`, which is only triggered on change of these properties and that's why their initial values aren't taken into account. I fixed that in 891e5e8e0a3d42967764831cb19ac8f917f3b830 by attempting to validate each value of `value` and `hsTariffNumber` instead (using Combine). 

Another way (simpler way) to fix it is to keep the property observers and trigger the validation in the initializer as well, to make sure that initial values are also validated. But I figure I can keep the similar checks in one place with Combine so I chose that route instead 😅.

I understand there are so much complicated logic in this PR - I struggled to put them together too since there are so many states to take care of. I agree that it'd be nice to have an extra pair of eyes to review this, so I'll ask the team for help!

2021-08-23 12:57 UTC, rachelmcr approved these changes
Thanks for the explanation, makes sense and the changes look good. 👍  I tested and confirmed that it works as expected now.

I'm approving the PR and will leave it up to you whether you want to wait for another set of eyes on this.

2021-08-25 01:52 UTC, merged