Shipping Labels: update carriers and rates step to accept multi packages
woocommerce/woocommerce-ios pull request #5125
Opened 2021-10-04 13:27 UTC by pmusolino

Closes #4716 

## Description
I updated the Shipping Label Carriers and Rates screen and view models to accept the multi packages. Now, the view will accept an array of packages and will return an array of rates, plus the sections of every package are compactable. 

## Changes
- Removed the unnecessary init methods in `ShippingLabelPackageSelected`.
- `ShippingLabelSelectedRate` now conforms to `Copiable`.
- Create a new SwiftUI view called `ShippingLabelCarrierSectionHeader` which represent the compactable header in the Carriers screen.
- Updated the `ShippingLabelCarriers` view for accepting an array of `ShippingLabelSelectedRate`, plus implemented a subview `ShippingLabelCarriersSection` which will represent a single compactable section.
- `ShippingLabelCarriersViewModel`: the rows have become sections, each section will contain the rows.
- Updated the unit tests.

## Testing
#### Case 1: Single package
1. Select Create Shipping Label, proceed to fill all information. In Package Details, keep everything in one package.
2. Proceed to the Carriers and Rate selection.
3. Select the carrier and rate and press "Done".
4. Re-open the screen, the previous rate selected should be still selected.
5. Proceed, and buy the shipping label.

#### Case 2: Multiple packages
1. Select Create Shipping Label, proceed to fill all information. In Package Details, keep everything in multiple packages (two or more).
2. Proceed to the Carriers and Rate selection.
3. You should be able to select the carrier and rates for all the packages. The "Done" button will be enabled only when you will select a rate for all the packages.
4. Re-open the screen, the previous rates selected should be still selected.
5. Proceed, and buy the shipping labels.

## Screenshot
<img src="https://user-images.githubusercontent.com/495617/135858724-618b575a-f8c9-4717-958a-1690c60f7b30.png" width=300 />

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-10-05 04:58 UTC, itsmeichigo reviewed
Thanks a lot for updating this view for multi-package support!

It seems like we haven't handled packages in original packaging when mapping from package attributes to `ShippingLabelPackageSelected`. So if I ship one of the items in its original package, I cannot find the package in the carriers screen:
https://user-images.githubusercontent.com/5533851/135964327-5ca9ad6c-6964-460a-8e86-53affc921318.mp4

I've found another minor issue regarding edge-to-edge layout in landscape mode (along with a couple of nits) that I've left in the comments down below. 

💡 A suggestion: should we also show an error icon on the header of each section if no rate is selected for that package yet? I think that way it'd be clearer for user why the Done button is not enabled.

2021-10-05 04:58 UTC, itsmeichigo commented on WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriers.swift
>                          .padding(.horizontal, insets: geometry.safeAreaInsets)
We may not need the padding here - instead how about adding padding for content of the section instead? Because it looks like the section is not extending edge-to-edge on landscape mode:

![Simulator Screen Shot - iPhone 12 Pro - 2021-10-05 at 10 27 37](https://user-images.githubusercontent.com/5533851/135956315-e881b719-e470-4a27-8adf-fef2ab4bceae.png)

2021-10-05 04:58 UTC, itsmeichigo commented on WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/ShippingLabelFormViewController.swift
> +                                                       .reduce(0, +),
Nit: I think it'd be better if we extract this into a variable so that we don't have to repeat the calculation in several places?

2021-10-05 04:58 UTC, itsmeichigo commented on WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriersSectionViewModel.swift
> +    var rows: [ShippingLabelCarrierRowViewModel] = []
Nit: I think we should keep `rows` as a constant?

2021-10-05 05:00 UTC, itsmeichigo commented on WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriers.swift
>                          .padding(.horizontal, insets: geometry.safeAreaInsets)
Also, it seems like there's some extra horizontal padding on the header that we don't need.

2021-10-05 17:10 UTC, pmusolino commented
Thank you @itsmeichigo for testing it. I fixed all the nits, but I'm still investigating the items shipped in original packages. I didn't consider that we will not be able to find the package ID (which is custom and always `individual`). In that case, we are not considering it at all when we are generating the selected packages. I'm going to change this behavior to handle also the items shipped in original packaging.

2021-10-06 13:48 UTC, pmusolino commented
@itsmeichigo can you do a second check? Now everything should be ok with the original packaging.

2021-10-07 05:51 UTC, itsmeichigo requested changes
Thank you for fixing the issue with the original packaging, I tested again and it works as expected! 🎉

However I noticed another issue just now 🤦‍♀️ . We're using `customsForms.first(where: { $0.packageID == boxID })` to find the matching customs form, which can be incorrect if we have several packages of the same ID.  

My suggestion is to have a unique ID for every package that ties customs form, selected package and selected rate all together. [Here](https://github.com/woocommerce/woocommerce-ios/compare/issue/4716-update-carriers-step-to-accept-multi-packages-main-logic...huong/shipping-label-attribute-update?expand=1) is how I imagine it could work. WDYT?

I also created a separated issue #5152 for further UI enhancements.

2021-10-07 05:54 UTC, itsmeichigo commented on WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriersViewModel.swift
> +            let rows: [ShippingLabelCarrierRowViewModel] = resp.defaultRates.map { rate in
I also missed this earlier - in cases where no rates can be found for a package, this map will result in the missing row for that package. We should instead map rows by packages, and find the rates that match the package ID instead. How does that sound?

2021-10-07 11:20 UTC, pmusolino commented
> However I noticed another issue just now 🤦‍♀️ . We're using customsForms.first(where: { $0.packageID == boxID }) to find the matching customs form, which can be incorrect if we have several packages of the same ID.
My suggestion is to have a unique ID for every package that ties customs form, selected package and selected rate all together. Here is how I imagine it could work. WDYT?

You are right, this is not ideal if we have several packages of the same ID, and your solution seems to work ok, so feel free to open a PR targeting this PR 🙇

2021-10-07 11:29 UTC, pmusolino commented on WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriersViewModel.swift
> +            let rows: [ShippingLabelCarrierRowViewModel] = resp.defaultRates.map { rate in
If there is no rate for a package, I believe we should consider displaying the empty state, since it's mandatory for us to choose a rate for every package. In that case, we should compare the number of `packages` with the number of `sections`. They should match, and every section should contain at least 1 row. Otherwise, we should show an error, as it will not be possible to continue. WDYT?

2021-10-08 03:28 UTC, itsmeichigo commented on WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriersViewModel.swift
> +            let rows: [ShippingLabelCarrierRowViewModel] = resp.defaultRates.map { rate in
Yes, I agree that we should show an error in that case, but I don't think displaying empty state screen is helpful for user since they may want to know which package needs updating. So how about we only display empty state when we cannot find rates for any package; otherwise we'll show a message under the empty sections only? Maybe a `ValidationErrorRow` is sufficient? We can bring this discussion to Slack to ask for design team's opinion and align with Android team.

2021-10-08 09:52 UTC, pmusolino commented on WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Carriers and Rates/ShippingLabelCarriersViewModel.swift
> +            let rows: [ShippingLabelCarrierRowViewModel] = resp.defaultRates.map { rate in
Thank you @itsmeichigo for your suggestion. As discussed on slack, and as reported here https://github.com/woocommerce/woocommerce-ios/issues/5171 we decided to align the behavior to Android displaying the empty state, and to wait for a design proposal to improve the error state in a next iteration. 👍

2021-10-08 10:40 UTC, pmusolino commented
@itsmeichigo ready for a final 👀

2021-10-08 10:54 UTC, itsmeichigo approved these changes
Everything looks good now, thank you for your patience 😅 :shipit:

2021-10-08 11:04 UTC, merged