Updated Wormholy from v1.6.4 to v1.6.5
woocommerce/woocommerce-ios pull request #5323
Opened 2021-11-02 14:46 UTC by pmusolino

This PR updates [Wormholy](https://github.com/pmusolino/Wormholy) from version 1.6.4 to version 1.6.5.

## Changes in v.1.6.5
- Fix: crash on iOS 15
- Fix authentication challenge handling to fix SSL pinning issue.
- Fix: keyboard content inset bug.
- Added an option for a default filter in the search bar.

## Testing
- Run `bundle exec pod install`.
- Try to open Wormholy from the Settings screen running the app in debug. It should work like before.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-11-03 20:37 UTC, allendav commented on Podfile.lock
> +  - UIDeviceIdentifier (1.6.0)
Why did this down rev?

2021-11-03 20:58 UTC, allendav requested changes
Tests fine. Tested on both an iPad running 14.8 and an iPhone running 15.1. Please double check the downrevving of UIDeviceIdentifier

2021-11-03 21:07 UTC, pmusolino commented
Good catch @allendav. Not sure why this happened, but a `pod repo update` before a `pod install` solved the issue.

2021-11-03 21:13 UTC, allendav commented
> Good catch @allendav. Not sure why this happened, but a pod repo update before a pod install solved the issue.

I still see 1.6.0 in the Podfile.lock here (and on my machine too even after PRU/PI)?

2021-11-05 16:06 UTC, pmusolino commented
@allendav after doing `bundle exec pod update UIDeviceIdentifier`, everything seems to be solved. Can you check it please? 🙇

2021-11-08 17:28 UTC, allendav commented
Looking now

2021-11-08 19:04 UTC, allendav approved these changes
:shipit:

2021-11-08 19:04 UTC, merged