Changed the order of statuses in filters to match the Order's lifecycle
woocommerce/woocommerce-ios pull request #6011
Opened 2022-01-28 20:01 UTC by chrisKns

Closes: #4457 

### Description
Currently the order that the list of statuses appear, in the select `Order Status` filters screen, is different from what Android displays. Android follows the more natural order that matches the Order's lifecycle. So this PR fixes the order in iOS to match that Android uses i.e. pending, processing, onHold, completed, cancelled, refunded, failed. Tested with the [latest version](https://github.com/woocommerce/woocommerce-android/commit/d675e7ef66a8085c1c872caf4f495df99fff5c5d) of the Android client. 

### Testing instructions

1. Launch the iOS client
2. Navigate to the `Orders` tab
3. Tap the `filter` button
4. Select the Order Status
5. Observe the order of the statuses. It should match the Order's lifecycle i.e. pending, processing, onHold, completed, cancelled, refunded, failed.

### Screenshots

After applying the fix the order of the status in the iOS client is the same as in the Android client, and follows the Order lifecycle:

<img src="https://user-images.githubusercontent.com/96764631/151608907-0343c48c-4889-4632-a62b-f4e70cfa0df1.png" width=35% height=35%> <img src="https://user-images.githubusercontent.com/96764631/151608901-42c4428d-85f9-41f4-a5f2-0cb656771e37.png" width=30% height=30%>

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-01-31 15:24 UTC, Ecarrion requested changes
Hi @chrisKns, congratulations on submitting your first PR!

Changes looks good but the original issue was referring to changing the order status list when modifying an order, not when filtering orders.

https://user-images.githubusercontent.com/562080/151820915-a9d8ade4-b6c7-4bd7-9e57-1e6cc330d361.mov

Could you please update the PR to include that(☝️) list? 
FYI is not necessary to delete what you have already changed!

2022-02-01 18:17 UTC, chrisKns commented
Thanks @Ecarrion ! You are right, I will update the PR fixing also the original issue

2022-02-04 17:24 UTC, chrisKns commented
@Ecarrion I pushed a commit that fixes the original issue ( the order status list when modifying an order).

https://user-images.githubusercontent.com/96764631/152574228-c858eb74-0081-4ea9-9067-229c536234ae.mp4


Since the FRC uses SQLite store we can not use a custom sort descriptor for performing the comparison. See [Fetch Predicates and Sort Descriptors](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/PersistentStoreFeatures.html).
So the only other solution was to sort them in memory after they are fetched.

I also added unit tests to validate the expected behaviour. (They also test that the the refunded status is not returned).

Also checked all other places where the ResultsController<StorageOrderStatus> is been used to fetch order statuses, and non of them are used to display to the user the list of statuses.

2022-02-05 01:17 UTC, Ecarrion approved these changes
This looks great! Thanks for adding unit tests!

2022-02-05 01:44 UTC, merged