Adding more menu button in product variations
woocommerce/woocommerce-ios pull request #6248
Opened 2022-02-20 15:32 UTC by chrisKns

Closes: #6238
Merge after #6247

### Description
Adds a new menu button in the navigation bar of the product variations list, that shows an action sheet with the "Cancel" and "Bulk Update" options. The "Bulk Update" will latter trigger an view in #6239.

### Testing instructions
1.  Go to Products
2. Select a product with variations
3. Select variations
4. In the top right there should exist a "more" button
5. Tapping the "more" button an action sheet is displayed
6. Tapping the "cancel" button dismisses the action sheet

### Screenshots
![Simulator Screen Shot - iPod touch (7th generation) - 2022-02-19 at 10 30 51](https://user-images.githubusercontent.com/96764631/154850194-3a607577-d7dd-438c-b5f4-bcf84061952e.png)

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-02-21 21:02 UTC, Ecarrion requested changes
Minor dependency injection request.
Also, I don't think you can use `trunk` as the base branch or the code won't compile because it's missing the "feature flag" commit.

2022-02-21 21:02 UTC, Ecarrion commented on WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
> +        }
We are trying to avoid accessing `ServiceLocator` properties directly as they become a nightmare to test and can product inconsistent tests, could you update this so the feature flag conditional is injected at the initializer, please?

2022-02-21 21:02 UTC, Ecarrion commented on WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
> +        }
I don't think we need any handler here right now, right?

2022-02-22 05:35 UTC, chrisKns commented on WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
> +        }
True this will not be needed. I removed it.

2022-02-22 05:37 UTC, chrisKns commented on WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
> +        }
Yes better to inject all dependencies, I have updated this to inject it thru the initializer.

2022-02-22 05:38 UTC, chrisKns commented
> Also, I don't think you can use `trunk` as the base branch or the code won't compile because it's missing the "feature flag" commit.

I was not sure what the proper etiquette was, so I just left a comment "Merge after #6247" in PR, it is better to wait first for all dependencies to be merged?

2022-02-23 20:35 UTC, Ecarrion approved these changes
Looks good! Thanks!

2022-02-23 20:35 UTC, merged