Track `signed_in` event during site credentials login
woocommerce/woocommerce-ios pull request #9014
Opened 2023-03-01 16:23 UTC by selanthiraiyan

- [ ] Please review  https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/748

## Description
This PR starts tracking the `signed_in` tracks event when the client handles the site credential login. 

## Testing instructions

Prerequiste - Create a JN site without Jetpack and with WooCommerce

- Install and launch the app 
- Tap "Enter Your Store Address" and enter the JN site
- Tap Continue and enter your wp-admin credentials in the next screen
- You should land in the dashboard screen
- From the Xcode console, ensure that the following event is tracked 
```
Tracked signed_in, properties: [:]
```

## Screenshots
NA

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-03-01 17:09 UTC, hichamboushaba commented
Thanks @selanthiraiyan for working on this, I have one remark, although I'm not 100% sure about my understanding of the code, it seems the event will be sent after the Cookie Nonce authentication succeeds and before the Application Passwords login checks (`PostSiteCredentialLoginChecker`) are executed, is this right?
If this is the case, I think it would be misleading, we need to send the success only when the user can actually use the app, which means all checks are successful, this is at least my understanding, and this is how it was done in Android.

2023-03-02 02:15 UTC, itsmeichigo requested changes
Thanks for the quick fix! But Hicham is correct; this event should only be tracked after all the checks [after](https://github.com/woocommerce/woocommerce-ios/blob/2816b4618ffeb5c6727af3026b5131f4da70c4bc/WooCommerce/Classes/Authentication/AuthenticationManager.swift#L698) the site credential login succeeds. This mean we won't need to update the authenticator library for this fix.

2023-03-02 02:42 UTC, selanthiraiyan commented
Thanks, @hichamboushaba and @itsmeichigo, for the review.

I have pushed the changes to track the event only after creating the application password.

As we are already near the next code freeze and release schedule, I am pointing the PR to `release/12.5` as a beta fix. 

Please let me know if we should do a hotfix instead. For a hotfix, I think I will have to request the platform team to prepare a `release/12.4.1` branch.

2023-03-02 03:41 UTC, itsmeichigo approved these changes
> Please let me know if we should do a hotfix instead. For a hotfix, I think I will have to request the platform team to prepare a release/12.4.1 branch.

I asked on a Slack thread [p1677728393554589-slack-CC7L49W13] to get advice from platform folks and Anitaa, let's wait for their response then.

2023-03-02 05:02 UTC, selanthiraiyan commented
@itsmeichigo I created [this new PR](https://github.com/woocommerce/woocommerce-ios/pull/9019) to target `release/12.4.1` as rebasing takes more effort. 

I am closing this PR.

2023-03-02 05:02 UTC, closed without merging